Update android.yml with build steps

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -46,7 +46,10 @@ jobs:
         env:
           FIREBASE_CONFIG: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON_BASE64 }}
         run: |
-          if [ -z "$FIREBASE_CONFIG" ]
+          if [ -z "$FIREBASE_CONFIG" ]; then
+            echo "Missing FIREBASE_CONFIG secret"
+            exit 1
+          fi
           echo "Decoding Firebase configuration from secrets"
           echo "$FIREBASE_CONFIG" | base64 -d > ./FenceWiseApp/app/google-services.json
 
